# Copy this content to your Streamlit App Dashboard -> Settings -> Secrets
# Do NOT commit your actual secrets (passwords) to GitHub!

GOOGLE_API_KEY = "AIzaSyAO_-HlHjthACxBuT4c1ych7xHD0e5j39g"

# MongoDB Connection String
MONGODB_URI = "mongodb+srv://chatbot_user:AvBa8SsMENcC7BbC@cluster0.tw4zqvm.mongodb.net/?appName=Cluster0"

# Admin Credentials
ADMIN_USERNAME = "admin"
# Hash for 'admin123' (SHA256)
ADMIN_PASSWORD_HASH = "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9"
